#!/bin/sh
# editar
MATERIA="bda"
INICIALES="mqr"

ARCHIVO="/etc/profile.d/99-custom-env.sh"
LINEA="alias sqlplus='rlwrap sqlplus'"
# cargar variables de entorno
. /etc/profile.d/99-custom-env.sh


# Verificar privilegios de root
if [ "$(id -u)" -ne 0 ]; then
    echo "Alto. Este script debe ejecutarse con privilegios de root"
    echo "Ejecutar así: sudo sh $0"
    exit 1
fi


# agregar linea en /etc/profile.d/99-custom-env.sh
if ! grep -qxF "${LINEA}" "${ARCHIVO}"; then
    echo "${LINEA}" >> "${ARCHIVO}"
    echo "Línea agregada exitosamente."
else
    echo "${LINEA} ya existe en ${ARCHIVO} No se hicieron cambios."
fi

# cambiar permisos a tnsnames
TNSNAMESFILE=${ORACLE_HOME}/network/admin/tnsnames.ora
chmod 755 ${TNSNAMESFILE}

# escribir nuevo nombre de servicio en archivo tnsnames
#cat << EOF > ${GLOGIN}
cat << EOF > ${TNSNAMESFILE}
# tnsnames.ora Network Configuration File: /opt/oracle/product/23ai/dbhomeFree/network/admin/tnsnames.ora
# Generated by Oracle configuration tools.

FREE =
  (DESCRIPTION =
    (ADDRESS = (PROTOCOL = TCP)(HOST = c1-${MATERIA}-${INICIALES})(PORT = 1521))
    (CONNECT_DATA =
      (SERVER = DEDICATED)
      (SERVICE_NAME = free.fi.unam)
    )
  )

LISTENER_FREE =
  (ADDRESS = (PROTOCOL = TCP)(HOST = c1-${MATERIA}-${INICIALES})(PORT = 1521))

${INICIALES}${MATERIA}_s1 =
  (DESCRIPTION =
    (ADDRESS = (PROTOCOL = TCP)(HOST = h1-${MATERIA}-${INICIALES}.fi.unam)(PORT = 1521))
    (CONNECT_DATA =
      (SERVER = DEDICATED)
      (SERVICE_NAME = ${INICIALES}${MATERIA}_s1.fi.unam)
    )
  )
EOF
echo "escrito en nombre de servicio [${INICIALES}${MATERIA}_s1] en el archivo ${TNSNAMESFILE}"
echo "ahora se vale conectarse asi sqlplus sys@${INICIALES}${MATERIA}_s1 as sysdba despues de iniciar listener y la cdb"

